function [fulldata] = read_SQL(id)
   % Set preferences
   prefs = setdbprefs('DataReturnFormat');
   setdbprefs('DataReturnFormat','table')
   % Connect the database
   conn = database('SQL', '', '');
   % Execute query and fetch results
   curs = exec(conn, ['SELECT  Instrument.ID'...
       ' , Instrument.CompanyName'...
       ' , Instrument.StockTicker'...
       ' , Instrument.Market'...
       ' , HistPrices.InstID'...
       ' , HistPrices.ClosePrice'...
       ' , HistPrices.Date'...
       ' FROM   ( MFM_Financial.FinData.HistPrices '...
       ' INNER JOIN MFM_Financial.FinData.Instrument '...
       ' ON    HistPrices.InstID = Instrument.ID )'...
       ' WHERE     Instrument.ID = ', id, '']);
   curs = fetch(curs);
   fulldata = curs.Data;
   close(conn);
   % Restore preferences
   setdbprefs('DataReturnFormat',prefs)
   %Clear variables
   clear curs conn